[tool.poetry]
name = "multifetcher"
version = "0.1.0"
description = "API for fetching URLs in parallel or one-by-one"
authors = ["Dmitriy Doroshev <dima@doroshev.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
